// AUTO-GENERATED by scripts/scrape_class_actions.py — do not edit by hand.
// Sources: classaction.org/settlements (structured) + Top Class Actions
// open-settlements archive via WP REST (bulk). Open settlements only.

export interface ClassAction {
  slug: string;
  name: string;
  claim_url: string;
  payout: string;
  deadline: string;
  proof: string;
  description: string;
}

export const classActions: ClassAction[] = [];
